### PR TITLE
Split examples into a seperate repository

### PR DESCRIPTION
**Pull request by jamienicol**
Hi,

Big fan of AdvTiledLoader, cheers for all the work on it.

Something which I think would make working with it nicer is if it could be used as a git submodule, but currently doing so also includes all the examples and makes the require path a bit funny.

This removes all the examples from the repository, and moves the contents of the AdvTiledLoader/ subdir into the root dir. This can then easily be included in other people's code by using the command  "git submodule add git://github.com/jamienicol/Advanced-Tiled-Loader.git AdvTiledLoader"

I've moved the examples to https://github.com/jamienicol/Advanced-Tiled-Loader-Examples 
That's also a clone of the existing repo, but git filter-branch has been used to remove the actual AdvTiledLoader library whilst keeping all the examples' history. I used the git submodule command shown above on that repo so it still works, but if you were to accept this merge then you'd obviously change the "jamienicol" part of that url to "Kadoba".

### CODE REVIEW

**Comment by Kadoba** [comment]
Let me think about this. I'll get back with you in the next couple of days.

**Comment by floriancargoet** [comment]
I second that, ATL as a git submodule would be nice.

**Comment by Kadoba** [comment]
All right. I've had time to go over git submodules and I'm convinced now. Sorry it took so long to respond.

**Comment by jamienicol** [comment]
awesome! thank you.

**Pull request merged**
