### PR TITLE
Fixed for 0.9.0

### PR DESCRIPTION
**Pull request by karai17**

### CODE REVIEW

**Comment by Clean3d** [comment]
This really helped me today. Thanks very much!

**Comment by Fayer** [comment]
This needs to be more visible!!

**Comment by utopiadev** [comment]
You are awesome.  I assume this is going to merged into main soon?

**Comment by karai17** [comment]
According to Kadoba, ATL is no longer going to be maintained so this is as far as my fix goes. :(

**Comment by utopiadev** [comment]
I saw that, is there any way someone else could act as the maintainer?  I tried to contact Kadoba about this, but I do not know the best way to do so.

**Comment by karai17** [comment]
I'm in talks with a few people to build a new Tiled library for love. If you're interested in participating, feel free to contact me in the #love IRC channel.

**Comment by karai17** [comment]
Thanks, Kadoba!

**Pull request merged**
